### ISSUE TITLE
Feature Request raise a 404 error

### ISSUE THREAD

**Issue by llaville** [composer-unused/symbol-parser#135]
## Describe the bug
New window https://github.com/composer-unused/symbol-parser/discussions/new?category=ideas was opened given a 404 error

## Additional information
From this panel : https://github.com/composer-unused/symbol-parser/issues/new/choose 
When a click on Open button

**Comment by llaville** [comment]
Same for Ask a Question 
Gave : https://github.com/composer-unused/symbol-parser/discussions/new?category=q-a with 404

**Comment by llaville** [comment]
@icanhazstring As I've a feature request to suggest, I'll wait that you fix your templates ;-)

**Comment by icanhazstring** [comment]
No pressure then? 😅

**Comment by icanhazstring** [comment]
No you can go for it :)

**Comment by llaville** [comment]
> Now you can go for it :)

Will do later. I'm busy for next 2 hours.
