### ISSUE TITLE
`ConsumedSymbolCollector` accept invalid strategies

### ISSUE THREAD

**Issue by llaville** [composer-unused/symbol-parser#148]
## Describe the bug
Class constructor of `ConsumeSymbolCollector` accept everything as input [1]

## Additional information
The checks is provided only for IDE with the phpDoc `@param array<StrategyInterface> $strategies` [2]

## Expected results 

Display an empty symbol list, because no valid strategy provided.

## Current results 

```text
Fatal error: Uncaught Error: Call to undefined method FooIsNotValidStrategy::canHandle() in /shared/backups/forks/symbol-parser/src/Parser/PHP/ConsumedSymbolCollector.php on line 43
```

## Script to reproduce issue

```php
<?php

use ComposerUnused\SymbolParser\Parser\PHP\ConsumedSymbolCollector;
use ComposerUnused\SymbolParser\Parser\PHP\SymbolNameParser;
use PhpParser\NodeVisitor\NameResolver;
use PhpParser\ParserFactory;

require_once __DIR__ . '/vendor/autoload.php';

class FooIsNotValidStrategy
{
}

$strategies = [
    new FooIsNotValidStrategy()
];

$symbolNameParser = new SymbolNameParser(
    (new ParserFactory())->createForNewestSupportedVersion(),
    new NameResolver(),
    new ConsumedSymbolCollector($strategies)
);

$code = <<<'CODE'
    <?php
    namespace My\Space;
CODE;

$symbols = iterator_to_array($symbolNameParser->parseSymbolNames($code));

var_dump($symbols);
```

[1] : https://github.com/composer-unused/symbol-parser/blob/0.2.2/src/Parser/PHP/ConsumedSymbolCollector.php#L31-L34
[2] : https://github.com/composer-unused/symbol-parser/blob/0.2.2/src/Parser/PHP/ConsumedSymbolCollector.php#L29

**Comment by icanhazstring** [comment]
Fixed with #149
