### ISSUE TITLE
Feature: Parse FunctionCall usage

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/symbol-parser#2]
Mentioned in: https://github.com/composer-unused/composer-unused/issues/242

Currently its impossible to check if a function was called as part of a consumed symbol.
This should be added as `FunctionCallStrategy` using the `FuncCall` AST node.

Import with `UseStrategy` is already covered.

**Comment by distantnative** [comment]
Would be great if this covers global function polyfills as well, e.g. https://github.com/symfony/polyfill

**Comment by icanhazstring** [comment]
Let me check what I can do 👍
