### ISSUE TITLE
Defined interfaces not recognized by DefinedSymbolCollector

### ISSUE THREAD

**Issue by samuelnogueira** [composer-unused/symbol-parser#41]
## Describe the bug
[Object interfaces](https://www.php.net/manual/en/language.oop5.interfaces.php) are not recognized by `\ComposerUnused\SymbolParser\Parser\PHP\DefinedSymbolCollector` as a symbol provided by a dependency.

## Error dump
n/a

## Additional information
**Given** a PHP file with the following content:
```php
<?php

namespace Foo;

interface Template
{
}
```

**Expected** a `SymbolNameParser` with a `DefinedSymbolCollector` visitor to yield `['Foo\\Template']` on `parseSymbolNames`, `[]` returned instead.

**Comment by samuelnogueira** [comment]
Not sure this should be reported here as a bug or a feature, but the behavior of `icanhazstring/composer-unused` seems buggy to me since libraries which only provide interfaces are not identified as used.

**Comment by icanhazstring** [comment]
Thanks for the report and fix. Will tag this and move it to composer-unused.
