### ISSUE TITLE
AnnotationStrategy runs out of memory

### ISSUE THREAD

**Issue by internalsystemerror** [composer-unused/symbol-parser#66]
## Describe the bug
When trying to use `composer-unused` on a small(ish) package, it runs out of memory trying to allocate 17GB.

> PHP Fatal error:  Out of memory (allocated 17205039104) (tried to allocate 34359738376 bytes) in /home/username/vendor-name/package-name/vendor/composer-unused/symbol-parser/src/Parser/PHP/Strategy/AnnotationStrategy.php on line 165

## Error dump
None created, and no extra output logged when using `-vvv` so I'm unsure what exactly is the cause.

## Additional information
No memory limit when running on CLI I believe, but either way 17GB is extremely excessive, especially for this relatively small package.

**Comment by icanhazstring** [comment]
Thanks for the report. Can you give me some info about the project you are scanning? So I can reproduce it.

**Comment by internalsystemerror** [comment]
It's a pretty simple mezzio+twig project and I'm still able to reproduce this. I don't really have a way to find out which part of my code is causing the memory issues though. Running `composer-unused` on ~60 lib packages and ~5 other apps has no issues whatsoever.

Any suggestions on how I could get some better debug information here? I do use array shapes and things a fair amount, so it could be related to this somehow?

**Comment by icanhazstring** [comment]
It's pretty hard to pinpoint. As there might be an issue in the parsing. But I don't know what it really is. 

I think something is causing an endless loop. So i probably would have to run a profile on the process to figure out which method it is. Then I can dig deeper to root cause and reproduce it.

But right now I don't have much time to work on it.

**Comment by internalsystemerror** [comment]
I have been able to narrow it down to the docblock in the following class method:

```php
<?php

declare(strict_types=1);

namespace App;

final class SomeClass
{

    /**
     * @return array{
     *     KeyName1?: non-empty-list<non-empty-string>,
     *     KeyName2?: non-empty-list<non-empty-string>,
     *     KeyName3?: non-empty-list<non-empty-string>,
     *     KeyName4?: non-empty-list<non-empty-string>,
     *     KeyName5?: non-empty-list<non-empty-string>,
     *     KeyName6?: non-empty-list<non-empty-string>,
     *     KeyName7?: non-empty-list<non-empty-string>,
     *     KeyName8?: non-empty-list<non-empty-string>,
     *     KeyName9?: non-empty-list<non-empty-string>,
     *     KeyName10?: non-empty-list<non-empty-string>,
     *     KeyName11?: non-empty-list<non-empty-string>,
     *     KeyName12?: non-empty-list<non-empty-string>,
     *     KeyName13?: non-empty-list<non-empty-string>,
     *     KeyName14?: non-empty-string,
     *     KeyName15?: non-empty-string,
     *     KeyName16?: non-empty-string,
     *     KeyName17?: non-empty-string,
     *     KeyName18?: non-empty-string,
     *     KeyName19?: non-empty-string,
     *     KeyName20?: non-empty-string,
     *     KeyName21?: non-empty-string,
     *     KeyName22?: non-empty-string,
     *     KeyName23?: non-empty-string,
     *     KeyName24?: non-empty-string,
     *     KeyName25?: non-empty-string,
     *     KeyName26?: non-empty-string
     * }
     */
    public function someMethod(): array
    {
        return [];
    }
}
```

**Comment by icanhazstring** [comment]
Holy shit. Ok that's a huge one.
Will check using that. 👍
