### ISSUE TITLE
Undefined property ConstFetch::$value in FileInclude.php on line 24

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/symbol-parser#86]
Reported by @wirone via twitter:

https://twitter.com/_Codito_/status/1633141256636203008

**Comment by Wirone** [comment]
The root cause of those errors is like this:

```php
$filename = __DIR__ . DIRECTORY_SEPARATOR . sprintf(
    '%s.php',
    ltrim(str_replace('\\', '/', $class), 'Foo/')
);
if (is_readable($filename)) {
    require $filename;
}
```

In `FileInclude::resolveConcatOperation()` the `$rightOperand` is a `DIRECTORY_SEPARATOR`:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/600668/223564631-16a8a2f2-cf83-4cff-a30a-93f24978885c.png">

**Comment by icanhazstring** [comment]
Ok, will probably have to resolve the right operand down to a string, same as left.

**Comment by icanhazstring** [comment]
Hm. After investigation, this seems nearly impossible using static analysis.
The reason is I would have to execute that part to even be able to parse the `$filename` (maybe with `eval` 🙈 )

**Comment by Wirone** [comment]
I think the most important thing here is to prevent invalid call, and I see you did it in #89 so 👍 . Support for complex paths can be added later as improvement, the bug was fixed 🙂.
